
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

ENV CONFIG_PATH=k8s-specifications/vote-deployment.yaml

CMD ["python", "main.py"]